{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-jpa",
    "version": "2.6.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.2",
      "buildId": "hwcihbirxbecdaqfz47uice33q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.6.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.6.5"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.7.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.6.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.17"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.5.jar",
          "url": "spring-boot-starter-data-jpa-2.6.5.jar",
          "size": 4758,
          "sha512": "7c892316de5c5eda4e7f3b36d48b403c2dff14dc51ec6df6f776e05587edbfde769fa952bc631f6b300377e6ea74d98e22d93de556781d5095267c1eca175357",
          "sha256": "f059975cc2a31828841f50420cad3cc77f4a268f54f4ae0d48a01a20c13b8f70",
          "sha1": "8021867a0f7369de293dd15f6141aff375f8f736",
          "md5": "922b96f56d6613e32d792736440d296b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.6.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.6.5"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.7.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.6.3"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.17"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.5.jar",
          "url": "spring-boot-starter-data-jpa-2.6.5.jar",
          "size": 4758,
          "sha512": "7c892316de5c5eda4e7f3b36d48b403c2dff14dc51ec6df6f776e05587edbfde769fa952bc631f6b300377e6ea74d98e22d93de556781d5095267c1eca175357",
          "sha256": "f059975cc2a31828841f50420cad3cc77f4a268f54f4ae0d48a01a20c13b8f70",
          "sha1": "8021867a0f7369de293dd15f6141aff375f8f736",
          "md5": "922b96f56d6613e32d792736440d296b"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.5.jar",
          "url": "spring-boot-starter-data-jpa-2.6.5.jar",
          "size": 4758,
          "sha512": "7c892316de5c5eda4e7f3b36d48b403c2dff14dc51ec6df6f776e05587edbfde769fa952bc631f6b300377e6ea74d98e22d93de556781d5095267c1eca175357",
          "sha256": "f059975cc2a31828841f50420cad3cc77f4a268f54f4ae0d48a01a20c13b8f70",
          "sha1": "8021867a0f7369de293dd15f6141aff375f8f736",
          "md5": "922b96f56d6613e32d792736440d296b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.6.5"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.5.jar",
          "url": "spring-boot-starter-data-jpa-2.6.5.jar",
          "size": 4758,
          "sha512": "7c892316de5c5eda4e7f3b36d48b403c2dff14dc51ec6df6f776e05587edbfde769fa952bc631f6b300377e6ea74d98e22d93de556781d5095267c1eca175357",
          "sha256": "f059975cc2a31828841f50420cad3cc77f4a268f54f4ae0d48a01a20c13b8f70",
          "sha1": "8021867a0f7369de293dd15f6141aff375f8f736",
          "md5": "922b96f56d6613e32d792736440d296b"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.6.5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.5-javadoc.jar",
          "url": "spring-boot-starter-data-jpa-2.6.5-javadoc.jar",
          "size": 4749,
          "sha512": "b9ce694fc4b10338442e8077b782d3e97e28f0781a9475bb2a91b8b6cc8b651bafe7985ce86d1741f39aa4249713a9c1db05c92cf3ec2404a13a739f3d3c500f",
          "sha256": "1151fb1e31473a59477e77e2f19d9938a1d3ce73f936f2ce42b959248c20e199",
          "sha1": "3c65bdc994c12fd531b52a5390693d87814f5da3",
          "md5": "36637b3012319b99f5a8846b27e1e9d2"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.6.5-sources.jar",
          "url": "spring-boot-starter-data-jpa-2.6.5-sources.jar",
          "size": 4747,
          "sha512": "2c5f2bb63cd162af565001a0e8a9bde66d6909666f176c449caa4adc5bbc1ac3738a173ef49a8892b436842c120a3541265880b9e61fcd6654d81d765205e3ce",
          "sha256": "206565f1ea850e5fd190b518547a4164df48232218cd79a6ccc332f2a66085ff",
          "sha1": "7710f4ebe60d8511d2ea6f49793e4d3ddf4424af",
          "md5": "225915e9ebb05fa7195df6f870fdb67e"
        }
      ]
    }
  ]
}
