{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-jpa",
    "version": "2.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.2",
      "buildId": "zn6xqxn44ncgdbozihl4cdadiy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.10.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.22"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.3.jar",
          "url": "spring-boot-starter-data-jpa-2.7.3.jar",
          "size": 4758,
          "sha512": "c511ebe36644135469b4b2956087459523434f1dc4631a3ee6b26ab216caaa72a247b8ebc2f36195a74476d19c4fa5aaedd327c729e216abbf81e3b5d2280f97",
          "sha256": "511eb0516e3f26c76fa0a7f6831d3638681b00d782c797034fdd205fc399fdd5",
          "sha1": "23f7118584200cf9edd43140dc6252679047bee0",
          "md5": "5f79d2d0132abad21b96371b310b3c5d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.7.3"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.6.10.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.7.2"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.3.22"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.3.jar",
          "url": "spring-boot-starter-data-jpa-2.7.3.jar",
          "size": 4758,
          "sha512": "c511ebe36644135469b4b2956087459523434f1dc4631a3ee6b26ab216caaa72a247b8ebc2f36195a74476d19c4fa5aaedd327c729e216abbf81e3b5d2280f97",
          "sha256": "511eb0516e3f26c76fa0a7f6831d3638681b00d782c797034fdd205fc399fdd5",
          "sha1": "23f7118584200cf9edd43140dc6252679047bee0",
          "md5": "5f79d2d0132abad21b96371b310b3c5d"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.3.jar",
          "url": "spring-boot-starter-data-jpa-2.7.3.jar",
          "size": 4758,
          "sha512": "c511ebe36644135469b4b2956087459523434f1dc4631a3ee6b26ab216caaa72a247b8ebc2f36195a74476d19c4fa5aaedd327c729e216abbf81e3b5d2280f97",
          "sha256": "511eb0516e3f26c76fa0a7f6831d3638681b00d782c797034fdd205fc399fdd5",
          "sha1": "23f7118584200cf9edd43140dc6252679047bee0",
          "md5": "5f79d2d0132abad21b96371b310b3c5d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.7.3"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.3.jar",
          "url": "spring-boot-starter-data-jpa-2.7.3.jar",
          "size": 4758,
          "sha512": "c511ebe36644135469b4b2956087459523434f1dc4631a3ee6b26ab216caaa72a247b8ebc2f36195a74476d19c4fa5aaedd327c729e216abbf81e3b5d2280f97",
          "sha256": "511eb0516e3f26c76fa0a7f6831d3638681b00d782c797034fdd205fc399fdd5",
          "sha1": "23f7118584200cf9edd43140dc6252679047bee0",
          "md5": "5f79d2d0132abad21b96371b310b3c5d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-jpa-maven-optional",
          "version": "2.7.3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.3-javadoc.jar",
          "url": "spring-boot-starter-data-jpa-2.7.3-javadoc.jar",
          "size": 4749,
          "sha512": "11cdf95a5f79f503aa042804e9a1d8301d79b7065cc7a56dd54fe87f72d341878bcc4ab664a1c1a5e47f057f966a4d14cee45a664636185b874ec31ef9531f6a",
          "sha256": "f45036b27ed9b3134e7d5c89c4ac81921c282208992a7e40b515549b6449db8b",
          "sha1": "4d02a8f7461daf2102a28208cac7eaefc2aab227",
          "md5": "5ad4c2f84ececeebc80e85839d424858"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.7.3-sources.jar",
          "url": "spring-boot-starter-data-jpa-2.7.3-sources.jar",
          "size": 4747,
          "sha512": "6b7a817ea4df3545281a2d1d4f891f8b0cb3b4f5a5261e5bd5a7f5073f7ce3e89a48bd0a259bc195120ad691c2fac374ff2c3473005860815e1b8acaf9aa80a4",
          "sha256": "9dd242e1835c1f22b3c6792cf5c78f1740216e84f33e7ff571a351d54b02b642",
          "sha1": "5c7eaa45de98f88a835d5e9a244fbdfa271d24fe",
          "md5": "ae7b4e2c443133761f39fa3598d698c3"
        }
      ]
    }
  ]
}
