{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-jpa",
    "version": "2.3.4.RELEASE",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.6.1",
      "buildId": "ozvmturbfbehjjvszcfxel53ra"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.4.21.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.3.4.RELEASE"
          },
          "excludes": [
            {
              "group": "org.aspectj",
              "module": "aspectjrt"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.3.4.RELEASE.jar",
          "url": "spring-boot-starter-data-jpa-2.3.4.RELEASE.jar",
          "size": 4753,
          "sha512": "89e84c530db6986d04223b86a1a3d2ee450db9eabf17c93fea259e528f776e845cf04cbf7532a5b2caa505e62f73b43cd377e78c6bad1a825963efd26cdb8345",
          "sha256": "0695cdd777334c4d019c6230ef6a9a76151d7cd052a3345050664727aaf7d382",
          "sha1": "a8b9828649248d762d1d3fc6898c8d7e471e1a8e",
          "md5": "60ad5e9f911ea706615e2fd09289395d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-aop",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "2.3.4.RELEASE"
          }
        },
        {
          "group": "jakarta.transaction",
          "module": "jakarta.transaction-api",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "jakarta.persistence",
          "module": "jakarta.persistence-api",
          "version": {
            "requires": "2.2.3"
          }
        },
        {
          "group": "org.hibernate",
          "module": "hibernate-core",
          "version": {
            "requires": "5.4.21.Final"
          },
          "excludes": [
            {
              "group": "javax.xml.bind",
              "module": "jaxb-api"
            },
            {
              "group": "javax.activation",
              "module": "javax.activation-api"
            },
            {
              "group": "javax.persistence",
              "module": "javax.persistence-api"
            },
            {
              "group": "org.jboss.spec.javax.transaction",
              "module": "jboss-transaction-api_1.2_spec"
            }
          ]
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-jpa",
          "version": {
            "requires": "2.3.4.RELEASE"
          },
          "excludes": [
            {
              "group": "org.aspectj",
              "module": "aspectjrt"
            }
          ]
        },
        {
          "group": "org.springframework",
          "module": "spring-aspects",
          "version": {
            "requires": "5.2.9.RELEASE"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.3.4.RELEASE.jar",
          "url": "spring-boot-starter-data-jpa-2.3.4.RELEASE.jar",
          "size": 4753,
          "sha512": "89e84c530db6986d04223b86a1a3d2ee450db9eabf17c93fea259e528f776e845cf04cbf7532a5b2caa505e62f73b43cd377e78c6bad1a825963efd26cdb8345",
          "sha256": "0695cdd777334c4d019c6230ef6a9a76151d7cd052a3345050664727aaf7d382",
          "sha1": "a8b9828649248d762d1d3fc6898c8d7e471e1a8e",
          "md5": "60ad5e9f911ea706615e2fd09289395d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.3.4.RELEASE-javadoc.jar",
          "url": "spring-boot-starter-data-jpa-2.3.4.RELEASE-javadoc.jar",
          "size": 4753,
          "sha512": "89e84c530db6986d04223b86a1a3d2ee450db9eabf17c93fea259e528f776e845cf04cbf7532a5b2caa505e62f73b43cd377e78c6bad1a825963efd26cdb8345",
          "sha256": "0695cdd777334c4d019c6230ef6a9a76151d7cd052a3345050664727aaf7d382",
          "sha1": "a8b9828649248d762d1d3fc6898c8d7e471e1a8e",
          "md5": "60ad5e9f911ea706615e2fd09289395d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-jpa-2.3.4.RELEASE-sources.jar",
          "url": "spring-boot-starter-data-jpa-2.3.4.RELEASE-sources.jar",
          "size": 4753,
          "sha512": "a9b0c96fbd03b8b544b6f37f738842b07023e72a16e01d9bcd1b0d7ab4311b6d7dfd3ccf652729e3a535febc139b262c698b638531c5b77161f60ae43eb825d2",
          "sha256": "9ac2031aa10ee05c3d0900657dc88fda1a34562af9b79e5884fe5208d23eb64d",
          "sha1": "0082fc6e0b93994fc5372d8060f8138545e8cee5",
          "md5": "f52aa3c9ad49bb8c2fc24d2684ae6d1b"
        }
      ]
    }
  ]
}
