{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-tomcat",
    "version": "2.7.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.2",
      "buildId": "zn6xqxn44ncgdbozihl4cdadiy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.65"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.65"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.65"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.3.jar",
          "url": "spring-boot-starter-tomcat-2.7.3.jar",
          "size": 4796,
          "sha512": "416f7bd6b66e880b13f745d883995eec6f7a5be8110746f12ba1b3f3ddc5c2a51eae8fe3bee930be84a77b9b9563195a8f5f66de6c4158803bc9c80509d38621",
          "sha256": "d9696b94a38f237a58dee2b2d9620e2fb12ce4e73e4d23fbcfce12607885c528",
          "sha1": "7a5998baaa05d5e7a9af7194a21f2ac3512ba7a0",
          "md5": "903033ef3f3622647594bf95e4715722"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-core",
          "version": {
            "requires": "9.0.65"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-el",
          "version": {
            "requires": "9.0.65"
          }
        },
        {
          "group": "org.apache.tomcat.embed",
          "module": "tomcat-embed-websocket",
          "version": {
            "requires": "9.0.65"
          },
          "excludes": [
            {
              "group": "org.apache.tomcat",
              "module": "tomcat-annotations-api"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.3.jar",
          "url": "spring-boot-starter-tomcat-2.7.3.jar",
          "size": 4796,
          "sha512": "416f7bd6b66e880b13f745d883995eec6f7a5be8110746f12ba1b3f3ddc5c2a51eae8fe3bee930be84a77b9b9563195a8f5f66de6c4158803bc9c80509d38621",
          "sha256": "d9696b94a38f237a58dee2b2d9620e2fb12ce4e73e4d23fbcfce12607885c528",
          "sha1": "7a5998baaa05d5e7a9af7194a21f2ac3512ba7a0",
          "md5": "903033ef3f3622647594bf95e4715722"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.3.jar",
          "url": "spring-boot-starter-tomcat-2.7.3.jar",
          "size": 4796,
          "sha512": "416f7bd6b66e880b13f745d883995eec6f7a5be8110746f12ba1b3f3ddc5c2a51eae8fe3bee930be84a77b9b9563195a8f5f66de6c4158803bc9c80509d38621",
          "sha256": "d9696b94a38f237a58dee2b2d9620e2fb12ce4e73e4d23fbcfce12607885c528",
          "sha1": "7a5998baaa05d5e7a9af7194a21f2ac3512ba7a0",
          "md5": "903033ef3f3622647594bf95e4715722"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.7.3"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.3.jar",
          "url": "spring-boot-starter-tomcat-2.7.3.jar",
          "size": 4796,
          "sha512": "416f7bd6b66e880b13f745d883995eec6f7a5be8110746f12ba1b3f3ddc5c2a51eae8fe3bee930be84a77b9b9563195a8f5f66de6c4158803bc9c80509d38621",
          "sha256": "d9696b94a38f237a58dee2b2d9620e2fb12ce4e73e4d23fbcfce12607885c528",
          "sha1": "7a5998baaa05d5e7a9af7194a21f2ac3512ba7a0",
          "md5": "903033ef3f3622647594bf95e4715722"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-tomcat-maven-optional",
          "version": "2.7.3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.3-javadoc.jar",
          "url": "spring-boot-starter-tomcat-2.7.3-javadoc.jar",
          "size": 4745,
          "sha512": "0df6195f2e48c9194e85b8ff03ce1e0ac4f81edf49e2a516bf7460c766f95e9b24dd4b09fb432d883a60e1347ab3e31fe6b9a043a0217d4b21cfe3bddfe13800",
          "sha256": "7b9c8e6b7f92eef65adef49488f7243a09b5e474f02dff4451b2e12179ed2b1a",
          "sha1": "9e5561988b53d3b9612b4bc00a27730413c8d3d2",
          "md5": "51ddd4260aec1aff228acd4331409788"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-tomcat-2.7.3-sources.jar",
          "url": "spring-boot-starter-tomcat-2.7.3-sources.jar",
          "size": 4743,
          "sha512": "0305cb571fe97928b61d655d9b685c5c71903ef48f1a128cdf4424d7649ab3bb7edbc42bfaf51f34edcd9922ed47d2ecdbaba92fe4589d35fe070bf305120fae",
          "sha256": "8fa1f7464ef671a35c0d96330bf24e420463200dbfce03dd9c071bc23449b9a9",
          "sha1": "a8cab643a29454dc97e723607b6eca8184d4782b",
          "md5": "ba640787b7d3d77059fbf5d5f8604917"
        }
      ]
    }
  ]
}
