{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter",
    "version": "2.6.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.9.2",
      "buildId": "hwcihbirxbecdaqfz47uice33q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.6.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.6.5"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.17"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.6.5.jar",
          "url": "spring-boot-starter-2.6.5.jar",
          "size": 4770,
          "sha512": "29b76e9094a92d57ce03777ac063fa7594efc128849209146e599863bfe950b9c91fc594ab06334fe8fbd37d716eab541a0066540f0a907ac52b14252db8a7ee",
          "sha256": "13cc717fee9e85d8e9adb170ac1fa0ac44fc4ea6e2e0462f373a32b8871b3078",
          "sha1": "26a7cd427b33d44d1166097ad31cd49880efe695",
          "md5": "a4d8328d5bf705dbdbe8de6e3244ae18"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.6.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.6.5"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-logging",
          "version": {
            "requires": "2.6.5"
          }
        },
        {
          "group": "jakarta.annotation",
          "module": "jakarta.annotation-api",
          "version": {
            "requires": "1.3.5"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "5.3.17"
          }
        },
        {
          "group": "org.yaml",
          "module": "snakeyaml",
          "version": {
            "requires": "1.29"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-2.6.5.jar",
          "url": "spring-boot-starter-2.6.5.jar",
          "size": 4770,
          "sha512": "29b76e9094a92d57ce03777ac063fa7594efc128849209146e599863bfe950b9c91fc594ab06334fe8fbd37d716eab541a0066540f0a907ac52b14252db8a7ee",
          "sha256": "13cc717fee9e85d8e9adb170ac1fa0ac44fc4ea6e2e0462f373a32b8871b3078",
          "sha1": "26a7cd427b33d44d1166097ad31cd49880efe695",
          "md5": "a4d8328d5bf705dbdbe8de6e3244ae18"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.5.jar",
          "url": "spring-boot-starter-2.6.5.jar",
          "size": 4770,
          "sha512": "29b76e9094a92d57ce03777ac063fa7594efc128849209146e599863bfe950b9c91fc594ab06334fe8fbd37d716eab541a0066540f0a907ac52b14252db8a7ee",
          "sha256": "13cc717fee9e85d8e9adb170ac1fa0ac44fc4ea6e2e0462f373a32b8871b3078",
          "sha1": "26a7cd427b33d44d1166097ad31cd49880efe695",
          "md5": "a4d8328d5bf705dbdbe8de6e3244ae18"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.6.5"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.5.jar",
          "url": "spring-boot-starter-2.6.5.jar",
          "size": 4770,
          "sha512": "29b76e9094a92d57ce03777ac063fa7594efc128849209146e599863bfe950b9c91fc594ab06334fe8fbd37d716eab541a0066540f0a907ac52b14252db8a7ee",
          "sha256": "13cc717fee9e85d8e9adb170ac1fa0ac44fc4ea6e2e0462f373a32b8871b3078",
          "sha1": "26a7cd427b33d44d1166097ad31cd49880efe695",
          "md5": "a4d8328d5bf705dbdbe8de6e3244ae18"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-maven-optional",
          "version": "2.6.5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.5-javadoc.jar",
          "url": "spring-boot-starter-2.6.5-javadoc.jar",
          "size": 4738,
          "sha512": "60c8377cea3d5d17002b6973d58af2eee17f6671b9459b154455d99402536dda340070827b9484a4470987b69a0846e8163bc765a73d0ce6061524b673ebc1f4",
          "sha256": "ecbab6d4135370051c383de29b74fb2b1f9a637f0d2a1b0bd42ccb4acc963f2e",
          "sha1": "b8ee21c46688cf6b71528bde0ce9d53a23d9975c",
          "md5": "41c1b3d48b06ebb80f632f62f0bd98b6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-2.6.5-sources.jar",
          "url": "spring-boot-starter-2.6.5-sources.jar",
          "size": 4737,
          "sha512": "c918b8e16bb349a7f4f192728475d07898f726a53f53e415fd14389b62884247a3372fb8eb8110ae4e047377c6f1d80d6549626bd18a4e0bc0822b75caad06b6",
          "sha256": "4300b355ec1ea9d64429c249f74fa020c3e9febee0bdf7fde43df0f9597028b0",
          "sha1": "d4ead1154d76ee731298bfbb0f2e5118a4cbb6d9",
          "md5": "6fb5bb660b6643c724a5f8c5b65f3dfc"
        }
      ]
    }
  ]
}
